apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mac-m1-test-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  tls:
    - hosts:
        - mac-m1-test.sandbox.lib.umd.edu
      secretName: mac-m1-test.sandbox.lib.umd.edu-jasperserver-pro-tls-secret
  rules:
    - host:  mac-m1-test.sandbox.lib.umd.edu
      http:
        paths:
          - backend:
              service:
                name: mac-m1-test
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
